from normalized_columns import *

FMP = "fmp"
EODHD = "eodhd"

BALANCE = "balance"
INCOME = "income"
STATS = "statistics"
CASH = "cash"

# provider -> kind -> mapping
MAPPINGS = {
    FMP: {
        BALANCE: {
            "cashAndCashEquivalents" : "Cash and Cash Equivalents",
            "shortTermInvestments" : "Short Term Investments",
            "cashAndShortTermInvestments" : "Cash and Short Term Investments",
            "netReceivables" : "Accounts Receivable",
            "inventory" : "Inventory",
            "otherCurrentAssets" : "Other Current Assets",
            "totalCurrentAssets" : "Total Current Assets",
            "propertyPlantEquipmentNet" : "Property, Plant and Equipment",
            "longTermInvestments" : "Long Term Investments",
            "taxAssets" : "Tax Assets",
            "goodwill" : "Goodwill",
            "intangibleAssets" : "Intangible Assets",
            "otherNonCurrentAssets" : "Other Fixed Assets",
            "totalNonCurrentAssets" : "Fixed Assets",
            "otherAssets" : "Other Assets",
            "totalAssets" : "Total Assets",
            "accountPayables" : "Accounts Payable",
            "shortTermDebt" : "Short Term Debt",
            "taxPayables" : "Tax Payables",
            "deferredRevenue" : "Deferred Revenue",
            "otherCurrentLiabilities" : "Other Current Liabilities",
            "totalCurrentLiabilities" : "Total Current Liabilities",
            "longTermDebt" : "Long Term Debt",
            "deferredRevenueNonCurrent" : "Deferred Revenue Non Current",
            "deferredTaxLiabilitiesNonCurrent" : "Deferred Tax Liabilities",
            "otherNonCurrentLiabilities" : "Other Non Current Liabilities",
            "totalNonCurrentLiabilities" : "Total Non Current Liabilities",
            "otherLiabilities" : "Other Liabilities",
            "capitalLeaseObligations" : "Capital Lease Obligations",
            "totalDebt" : "Total Debt",
            "netDebt" : "Net Debt",
            "totalInvestments" : "Total Investments",
            "totalLiabilities" : "Total Liabilities",
            "preferredStock" : "Preferred Stock",
            "commonStock" : "Common Stock",
            "retainedEarnings" : "Retained Earnings",
            "accumulatedOtherComprehensiveIncomeLoss" : "Accumulated Other Comprehensive Income",
            "othertotalStockholdersEquity" : "Other Total Shareholder Equity",
            "totalStockholdersEquity" : "Total Shareholder Equity",
            "totalEquity" : "Total Equity",
            "totalLiabilitiesAndStockholdersEquity" : "Total Liabilities and Shareholder Equity",
            "minorityInterest" : "Minority Interest",
            "totalLiabilitiesAndTotalEquity" : "Total Liabilities and Equity",
        },
        CASH: {
            "netIncome" : "Net Income",
            "depreciationAndAmortization" : "Depreciation and Amortization",
            "deferredIncomeTax" : "Deferred Income Tax",
            "stockBasedCompensation" : "Stock Based Compensation",
            "changeInWorkingCapital" : "Change in Working Capital",
            "accountsReceivables" : "Accounts Receivables",
            "inventory" : "Inventory",
            "accountsPayables" : "Accounts Payables",
            "otherWorkingCapital" : "Other Working Capital",
            "otherNonCashItems" : "Other Non Cash Items",
            "netCashProvidedByOperatingActivities" : "Cash Flow from Operations",
            "investmentsInPropertyPlantAndEquipment" : "Property, Plant and Equipment",
            "acquisitionsNet" : "Acquisitions",
            "purchasesOfInvestments" : "Purchases of Investments",
            "salesMaturitiesOfInvestments" : "Sales of Investments",
            "otherInvestingActivites" : "Other Investing Activities",
            "netCashUsedForInvestingActivites" : "Cash Flow from Investing",
            "debtRepayment" : "Debt Repayment",
            "commonStockIssued" : "Common Stock Issued",
            "commonStockRepurchased" : "Common Stock Purchased",
            "dividendsPaid" : "Dividends Paid",
            "" : "Preferred Dividends Paid",
            "otherFinancingActivites" : "Other Financing Activities",
            "netCashUsedProvidedByFinancingActivities" : "Cash Flow from Financing",
            "effectOfForexChangesOnCash" : "Forex Changes on Cash",
            "netChangeInCash" : "Net Change in Cash",
            "cashAtEndOfPeriod" : "Cash End of Period",
            "cashAtBeginningOfPeriod" : "Cash Beginning of Period",
            "operatingCashFlow" : "Operating Cash Flow",
            "capitalExpenditure" : "Capital Expenditure",
            "freeCashFlow" : "Free Cash Flow",
        },
        INCOME: {
            "revenue" : "Revenue",
            "costOfRevenue" : "Cost of Goods Sold",
            "grossProfit" : "Gross Profit",
            "grossProfitRatio" : "Gross Profit Ratio",
            "researchAndDevelopmentExpenses" : "Research and Development Expenses",
            "generalAndAdministrativeExpenses" : "General and Administrative Expenses",
            "sellingAndMarketingExpenses" : "Selling and Marketing Expenses",
            "sellingGeneralAndAdministrativeExpenses" : "Selling, General and Administrative Expenses",
            "otherExpenses" : "Other Expenses",
            "operatingExpenses" : "Operating Expenses",
            "costAndExpenses" : "Cost and Expenses",
            "interestIncome" : "Interest Income",
            "interestExpense" : "Interest Expense",
            "depreciationAndAmortization" : "Depreciation and Amortization",
            "ebitda" : "EBITDA",
            "ebitdaratio" : "EBITDA Ratio",
            "operatingIncome" : "Operating Income",
            "operatingIncomeRatio" : "Operating Income Ratio",
            "totalOtherIncomeExpensesNet" : "Total Other Income",
            "incomeBeforeTax" : "Income Before Tax",
            "incomeBeforeTaxRatio" : "Income Before Tax Ratio",
            "incomeTaxExpense" : "Income Tax Expense",
            "netIncome" : "Net Income",
            "netIncomeRatio" : "Net Income Ratio",
            "eps" : "EPS",
            "epsdiluted" : "EPS Diluted",
            "weightedAverageShsOut" : "Weighted Average Shares",
            "weightedAverageShsOutDil" : "Weighted Average Shares Diluted",
        },
        STATS: {
            "reportedCurrency" : "Reported Currency",
            "cik" : "CIK ID",
            "fillingDate" : "Filling Date",
            "acceptedDate" : "Accepted Date",
            "calendarYear" : "Calendar Year",
            "period" : "Period",
            "link" : "SEC Link",
            "finalLink" : "Document Link",
        }
    }
}