#!/bin/bash 

set -eou pipefail

find . -name \*.py -exec sed -i 's/\"Cash and Cash Equivalents\"/CASH_AND_CASH_EQUIVALENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Short Term Investments\"/SHORT_TERM_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash and Short Term Investments\"/CASH_AND_SHORT_TERM_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accounts Receivable\"/NET_RECEIVABLES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Inventory\"/INVENTORY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Current Assets\"/OTHER_CURRENT_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Current Assets\"/TOTAL_CURRENT_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Property, Plant and Equipment\"/PROPERTY_PLANT_EQUIPMENT_NET/g' {} \;
find . -name \*.py -exec sed -i 's/\"Long Term Investments\"/LONG_TERM_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Tax Assets\"/TAX_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Goodwill\"/GOODWILL/g' {} \;
find . -name \*.py -exec sed -i 's/\"Intangible Assets\"/INTANGIBLE_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Fixed Assets\"/OTHER_NON_CURRENT_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Fixed Assets\"/TOTAL_NON_CURRENT_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Assets\"/OTHER_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Assets\"/TOTAL_ASSETS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accounts Payable\"/ACCOUNT_PAYABLES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Short Term Debt\"/SHORT_TERM_DEBT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Tax Payables\"/TAX_PAYABLES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Deferred Revenue\"/DEFERRED_REVENUE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Current Liabilities\"/OTHER_CURRENT_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Current Liabilities\"/TOTAL_CURRENT_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Long Term Debt\"/LONG_TERM_DEBT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Deferred Revenue Non Current\"/DEFERRED_REVENUE_NON_CURRENT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Deferred Tax Liabilities\"/DEFERRED_TAX_LIABILITIES_NON_CURRENT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Non Current Liabilities\"/OTHER_NON_CURRENT_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Non Current Liabilities\"/TOTAL_NON_CURRENT_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Liabilities\"/OTHER_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Capital Lease Obligations\"/CAPITAL_LEASE_OBLIGATIONS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Debt\"/TOTAL_DEBT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Net Debt\"/NET_DEBT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Investments\"/TOTAL_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Liabilities\"/TOTAL_LIABILITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Preferred Stock\"/PREFERRED_STOCK/g' {} \;
find . -name \*.py -exec sed -i 's/\"Common Stock\"/COMMON_STOCK/g' {} \;
find . -name \*.py -exec sed -i 's/\"Retained Earnings\"/RETAINED_EARNINGS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accumulated Other Comprehensive Income\"/ACCUMULATED_OTHER_COMPREHENSIVE_INCOME_LOSS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Total Shareholder Equity\"/OTHERTOTAL_STOCKHOLDERS_EQUITY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Shareholder Equity\"/TOTAL_STOCKHOLDERS_EQUITY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Equity\"/TOTAL_EQUITY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Liabilities and Shareholder Equity\"/TOTAL_LIABILITIES_AND_STOCKHOLDERS_EQUITY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Minority Interest\"/MINORITY_INTEREST/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Liabilities and Equity\"/TOTAL_LIABILITIES_AND_TOTAL_EQUITY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Net Income\"/NET_INCOME/g' {} \;
find . -name \*.py -exec sed -i 's/\"Depreciation and Amortization\"/DEPRECIATION_AND_AMORTIZATION/g' {} \;
find . -name \*.py -exec sed -i 's/\"Deferred Income Tax\"/DEFERRED_INCOME_TAX/g' {} \;
find . -name \*.py -exec sed -i 's/\"Stock Based Compensation\"/STOCK_BASED_COMPENSATION/g' {} \;
find . -name \*.py -exec sed -i 's/\"Change in Working Capital\"/CHANGE_IN_WORKING_CAPITAL/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accounts Receivables\"/ACCOUNTS_RECEIVABLES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Inventory\"/INVENTORY/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accounts Payables\"/ACCOUNTS_PAYABLES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Working Capital\"/OTHER_WORKING_CAPITAL/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Non Cash Items\"/OTHER_NON_CASH_ITEMS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash Flow from Operations\"/NET_CASH_PROVIDED_BY_OPERATING_ACTIVITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Property, Plant and Equipment\"/INVESTMENTS_IN_PROPERTY_PLANT_AND_EQUIPMENT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Acquisitions\"/ACQUISITIONS_NET/g' {} \;
find . -name \*.py -exec sed -i 's/\"Purchases of Investments\"/PURCHASES_OF_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Sales of Investments\"/SALES_MATURITIES_OF_INVESTMENTS/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Investing Activities\"/OTHER_INVESTING_ACTIVITES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash Flow from Investing\"/NET_CASH_USED_FOR_INVESTING_ACTIVITES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Debt Repayment\"/DEBT_REPAYMENT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Common Stock Issued\"/COMMON_STOCK_ISSUED/g' {} \;
find . -name \*.py -exec sed -i 's/\"Common Stock Purchased\"/COMMON_STOCK_REPURCHASED/g' {} \;
find . -name \*.py -exec sed -i 's/\"Dividends Paid\"/DIVIDENDS_PAID/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Financing Activities\"/OTHER_FINANCING_ACTIVITES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash Flow from Financing\"/NET_CASH_USED_PROVIDED_BY_FINANCING_ACTIVITIES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Forex Changes on Cash\"/EFFECT_OF_FOREX_CHANGES_ON_CASH/g' {} \;
find . -name \*.py -exec sed -i 's/\"Net Change in Cash\"/NET_CHANGE_IN_CASH/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash End of Period\"/CASH_AT_END_OF_PERIOD/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cash Beginning of Period\"/CASH_AT_BEGINNING_OF_PERIOD/g' {} \;
find . -name \*.py -exec sed -i 's/\"Operating Cash Flow\"/OPERATING_CASH_FLOW/g' {} \;
find . -name \*.py -exec sed -i 's/\"Capital Expenditure\"/CAPITAL_EXPENDITURE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Free Cash Flow\"/FREE_CASH_FLOW/g' {} \;
find . -name \*.py -exec sed -i 's/\"Revenue\"/REVENUE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cost of Goods Sold\"/COST_OF_REVENUE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Gross Profit\"/GROSS_PROFIT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Gross Profit Ratio\"/GROSS_PROFIT_RATIO/g' {} \;
find . -name \*.py -exec sed -i 's/\"Research and Development Expenses\"/RESEARCH_AND_DEVELOPMENT_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"General and Administrative Expenses\"/GENERAL_AND_ADMINISTRATIVE_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Selling and Marketing Expenses\"/SELLING_AND_MARKETING_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Selling, General and Administrative Expenses\"/SELLING_GENERAL_AND_ADMINISTRATIVE_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Other Expenses\"/OTHER_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Operating Expenses\"/OPERATING_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Cost and Expenses\"/COST_AND_EXPENSES/g' {} \;
find . -name \*.py -exec sed -i 's/\"Interest Income\"/INTEREST_INCOME/g' {} \;
find . -name \*.py -exec sed -i 's/\"Interest Expense\"/INTEREST_EXPENSE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Depreciation and Amortization\"/DEPRECIATION_AND_AMORTIZATION/g' {} \;
find . -name \*.py -exec sed -i 's/\"EBITDA\"/EBITDA/g' {} \;
find . -name \*.py -exec sed -i 's/\"EBITDA Ratio\"/EBITDARATIO/g' {} \;
find . -name \*.py -exec sed -i 's/\"Operating Income\"/OPERATING_INCOME/g' {} \;
find . -name \*.py -exec sed -i 's/\"Operating Income Ratio\"/OPERATING_INCOME_RATIO/g' {} \;
find . -name \*.py -exec sed -i 's/\"Total Other Income\"/TOTAL_OTHER_INCOME_EXPENSES_NET/g' {} \;
find . -name \*.py -exec sed -i 's/\"Income Before Tax\"/INCOME_BEFORE_TAX/g' {} \;
find . -name \*.py -exec sed -i 's/\"Income Before Tax Ratio\"/INCOME_BEFORE_TAX_RATIO/g' {} \;
find . -name \*.py -exec sed -i 's/\"Income Tax Expense\"/INCOME_TAX_EXPENSE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Net Income\"/NET_INCOME/g' {} \;
find . -name \*.py -exec sed -i 's/\"Net Income Ratio\"/NET_INCOME_RATIO/g' {} \;
find . -name \*.py -exec sed -i 's/\"EPS\"/EPS/g' {} \;
find . -name \*.py -exec sed -i 's/\"EPS Diluted\"/EPSDILUTED/g' {} \;
find . -name \*.py -exec sed -i 's/\"Weighted Average Shares\"/WEIGHTED_AVERAGE_SHS_OUT/g' {} \;
find . -name \*.py -exec sed -i 's/\"Weighted Average Shares Diluted\"/WEIGHTED_AVERAGE_SHS_OUT_DIL/g' {} \;
find . -name \*.py -exec sed -i 's/\"Reported Currency\"/REPORTED_CURRENCY/g' {} \;
find . -name \*.py -exec sed -i 's/\"CIK ID\"/CIK/g' {} \;
find . -name \*.py -exec sed -i 's/\"Filling Date\"/FILLING_DATE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Accepted Date\"/ACCEPTED_DATE/g' {} \;
find . -name \*.py -exec sed -i 's/\"Calendar Year\"/CALENDAR_YEAR/g' {} \;
find . -name \*.py -exec sed -i 's/\"Period\"/PERIOD/g' {} \;
find . -name \*.py -exec sed -i 's/\"SEC Link\"/LINK/g' {} \;
find . -name \*.py -exec sed -i 's/\"Document Link\"/FINAL_LINK/g' {} \;
